channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.2
  - scipy==1.13.1
name: mlflow-env
