name: W7 Promote to Production (Stage->Smoke->Gate)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Expose your remote MLflow to all steps
    env:
      MLFLOW_TRACKING_URI: http://54.147.138.39:8081

    defaults:
      run:
        working-directory: W7-D1-mlflow-adv

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify MLflow reachability
        run: |
          set -euo pipefail
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI" >> "$GITHUB_ENV"

          echo "[CHECK] Reachability (UI root)"
          curl -fsS --max-time 10 "$MLFLOW_TRACKING_URI" >/dev/null

          echo "[CHECK] MLflow Python client"
          . .venv/bin/activate
          python -c "import os; from mlflow.tracking import MlflowClient; c=MlflowClient(tracking_uri=os.environ['MLFLOW_TRACKING_URI']); print('[OK] MLflow reachable. Experiments:', len(c.search_experiments()))"

      # Idempotent bootstrap: ensure at least one Prod version exists
      - name: Ensure baseline Production exists (idempotent)
        run: |
          . .venv/bin/activate
          make train_v1 || true
          make promote VERSION=1 STAGE=Production DRY=false || true

      - name: Train new candidate (latest)
        run: |
          . .venv/bin/activate
          make train_v2 || true

      - name: Stage -> Smoke -> Gate -> Prod
        run: |
          . .venv/bin/activate
          make promote_latest_safe

      - name: Upload logs/artifacts (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: w7d4-prod-release
          path: |
            logs/audit.jsonl
            mlflow.log
          if-no-files-found: warn
